# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iTunes Artists' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iTunes Artists
  pod 'SwiftLint'
  pod 'Alamofire', '~> 4.9.0'
  pod "SkeletonView"
  pod 'AlamofireImage', '~> 3.5'

  target 'iTunes ArtistsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iTunes ArtistsUITests' do
    inherit! :complete
    # Pods for testing
  end

end
